# Generated by Django 5.2.15 on 2026-06-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('birth_date', models.CharField(max_length=20, verbose_name='出生年月')),
                ('ethnicity', models.CharField(default='汉族', max_length=20, verbose_name='民族')),
                ('hometown', models.CharField(max_length=100, verbose_name='籍贯')),
                ('political_status', models.CharField(choices=[('群众', '群众'), ('共青团员', '共青团员'), ('中共党员', '中共党员'), ('中共预备党员', '中共预备党员'), ('民主党派', '民主党派')], default='群众', max_length=20, verbose_name='政治面貌')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=50, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=20, verbose_name='QQ')),
                ('photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='个人照片')),
                ('specialties', models.TextField(blank=True, verbose_name='个人特长')),
                ('hobbies', models.TextField(blank=True, verbose_name='个人爱好')),
                ('future_plan', models.TextField(blank=True, verbose_name='未来10年规划')),
                ('verify_course', models.CharField(help_text='用于身份验证的课程名称，用户需输入姓名和此课程才能通过验证', max_length=100, verbose_name='验证课程')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人简历',
                'verbose_name_plural': '个人简历',
            },
        ),
        migrations.CreateModel(
            name='FavoriteWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='网站地址')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='members.profile', verbose_name='所属人员')),
            ],
            options={
                'verbose_name': '喜爱网站',
                'verbose_name_plural': '喜爱网站',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('semester', models.CharField(blank=True, max_length=30, verbose_name='学期')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='members.profile', verbose_name='所属人员')),
            ],
            options={
                'verbose_name': '所学课程',
                'verbose_name_plural': '所学课程',
            },
        ),
    ]
